LRQA-74405 | master
joshchong/liferay-portal pull request #549
Opened 2022-04-16 00:12 UTC by brookedalton

https://issues.liferay.com/browse/LRQA-74405

2022-04-16 00:12 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-04-18 22:55 UTC, joshchong requested changes
@brookedalton can you make the changes in my review comments and resend? thanks!

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			title = "Secret Web Content");
maybe we can rename the title of the WC to something that the reader is able to understand the purpose of right away. like something that conveys "employees eyes only". that way it would make it easier to follow what the use case is for and what we are testing.

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			userScreenName = "usersn");
just curious, how were you able to create a user and login with them without setting a password? I thought that was required unless something changed.

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +
are there existing macros that allow us do add custom fields via json or rest api?

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +
are there existing macros that allow us do configure a custom field for a user via json or rest api?

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			customFieldType = "true / false");
is this step needed?

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		Blueprints.addElement(element = "Custom JSON Element");
Instead of using a "Custom JSON Element" for this test, create a "Custom Element" instead (i.e. Elements admin > create new element) and then add that element to a blueprint.

The reason for this is that part of the acceptance criteria for LPS-147264 is that the custom field shows up as a template variable in the Predefined Variables sidebar. The test should assert that it's there. It doesn't have to test clicking it and adding it to the JSON though, bc I haven't found a way to edit individual lines within the code mirror editor yet.

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +
let's try to keep the element JSON as simple and short as possible, only including things that are absolutely necessary so we convey to the reader what is exactly needed for this use case to work. you might have to do some guess and checking to figure this out.

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +  },
e.g. you can remove this description line bc it's an optional field and not necessary for the test to work.

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +                "value": true
shouldn't this be "false"? by making it false we would be saying, if a user is not an employee, they should not see the employee web content.

2022-04-18 22:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +
reiterating what I was saying above, I think the search results assertions should be swapped. Employees should see the wc. non-employees shouldn't.

2022-04-19 20:51 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +
I couldn't find any existing macros :(

2022-04-19 20:52 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +
I couldn't find any existing macros :(

2022-04-20 22:39 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			userScreenName = "usersn");
@brookedalton were you able to figure this out?

2022-04-20 22:42 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +
@brookedalton can you add assertions based on my previous comment:

> ...part of the acceptance criteria for LPS-147264 is that the custom field shows up as a template variable in the Predefined Variables sidebar. The test should assert that it's there. It doesn't have to test clicking it and adding it to the JSON though, bc I haven't found a way to edit individual lines within the code mirror editor yet.

2022-04-20 22:59 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			userScreenName = "usersn");
Hey Josh! Sorry I thought I left a comment here yesterday, I must not have uploaded it but I don't think it is necessary with the token based logins: https://liferay.slack.com/archives/CL84ZPHAT/p1620668235443700

2022-04-20 23:06 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			userScreenName = "usersn");
Locally it is working although I'm not sure if it will be the same on CI

2022-04-20 23:11 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			userScreenName = "usersn");
thanks, I've created https://issues.liferay.com/browse/LRQA-74499 to investigate this for the rest of our search tests.

Can you try running this test on CI after you finish your next changes?

2022-04-21 02:18 UTC, brookedalton commented
ci:test:search

2022-04-21 02:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2989/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2989/jenkins-report.html">here</a>.</b></p>

2022-04-21 03:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:search - 2 out of 2 jobs passed in 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/277cb979d9e924b1215c59c1027045c120b6eb97">277cb979d9e924b1215c59c1027045c120b6eb97</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d555ededce68cda16413902338e2ddf3c0acdf67">d555ededce68cda16413902338e2ddf3c0acdf67</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3168">Acceptance Upstream DXP (master) #3168</a></p><details><summary><strong>ci:test:search - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2989/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/48906/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2989/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/2989/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/2989/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/2989/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-04-21 03:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2989/">test-portal-acceptance-pullrequest(master)#2989</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2989/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/549">joshchong#549</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1691196902">[master] ci:test:search - brookedalton &gt; joshchong - PR#549 - 2022-04-20[19:21:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/7918/">publish-testray-report#7918</a><br/></div></div>

2022-04-21 21:41 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			value1 = "user.custom.field.employee");
hey @brookedalton, sorry I should have been more clear. I meant could you add assertions that the variable shows up within the Predefined Variables sidebar section seen in the image below.

![variables](https://user-images.githubusercontent.com/14988026/164556293-362f35ae-500a-4ff0-ba43-227f4104fae3.jpg)

2022-04-22 16:52 UTC, brookedalton commented
ci:test:search:nocompile

2022-04-22 16:53 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-04-22 16:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1714/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1714/jenkins-report.html">here</a>.</b></p>

2022-04-22 17:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:search - 2 out of 2 jobs passed in 50 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8474f47072e7dea4c7805bb985cc9ffa2aa0aadf">8474f47072e7dea4c7805bb985cc9ffa2aa0aadf</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/53f2e4aa757f27b161d9b1fda048ee0a7fcb55a6">53f2e4aa757f27b161d9b1fda048ee0a7fcb55a6</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3178">Acceptance Upstream DXP (master) #3178</a></p><details><summary><strong>ci:test:search - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1714/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44192/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1714/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-33/jobs/test-portal-acceptance-pullrequest(master)/builds/1714/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-33/jobs/test-portal-acceptance-pullrequest(master)/builds/1714/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-33/jobs/test-portal-acceptance-pullrequest(master)/builds/1714/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-04-22 17:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1714/">test-portal-acceptance-pullrequest(master)#1714</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1714/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/549">joshchong#549</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1695009869">[master] ci:test:search - brookedalton &gt; joshchong - PR#549 - 2022-04-22[09:53:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/4477/">publish-testray-report#4477</a><br/></div></div>

2022-04-22 23:40 UTC, joshchong commented
@brookedalton see changes in https://github.com/joshchong/liferay-portal/pull/551

2022-04-22 23:40 UTC, closed without merging