LPS-163121 | master
joshchong/liferay-portal pull request #609
Opened 2022-09-30 18:03 UTC by brookedalton

https://issues.liferay.com/browse/LPS-163121

2022-09-30 19:46 UTC, joshchong requested changes

2022-09-30 19:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			value1 = "Description in English");
We can remove these assertions since it's already covered in another test

2022-09-30 19:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +
can we just navigate to the localized page directly by tacking on /es in the url? You can add a conditional within the Search.openSearchPage macro for this similar to what you did for Blueprints.openBlueprintsAdmin

2022-09-30 19:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		WaitForElementPresent.waitForLastScript();
why is this waitfor needed?

2022-09-30 19:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +	test ViewBlueprintOptionsWidgetLocalizedTitleAndDescription {
rename to ViewBlueprintLocalizationWithinBlueprintsOptionsWidget

2022-09-30 19:52 UTC, brookedalton commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		WaitForElementPresent.waitForLastScript();
When testing locally one time it failed here because the select button did not show up immediately and there was a loading circle

2022-09-30 19:54 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		WaitForElementPresent.waitForLastScript();
oh huh interesting. not sure i've seen that before

2022-10-01 02:32 UTC, joshchong commented
hey @brookedalton did this test pass anywhere?

2022-10-03 17:05 UTC, joshchong commented
ci:forward

2022-10-03 17:05 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-10-03 17:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/3480/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3480/jenkins-report.html">here</a>.</b></p>

2022-10-03 17:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/700a0b5588e6ac8dea98684d46eb113a345d5d59">700a0b5588e6ac8dea98684d46eb113a345d5d59</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brookedalton/liferay-portal/tree/LPS-163121">LPS-163121</a><br/>Branch GIT ID: <a href="https://github.com/brookedalton/liferay-portal/commit/7580998190f669a1c818c24bd624dcbca1ad1bcc">7580998190f669a1c818c24bd624dcbca1ad1bcc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3480/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3480/jenkins-report.html">here</a>.</h5></details></html>

2022-10-03 17:10 UTC, closed without merging

2022-10-03 17:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3480/">test-portal-source-format#3480</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3480/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/609">joshchong#609</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1996680320">[master] ci:test:sf - brookedalton &gt; joshchong - PR#609 - 2022-10-03[10:06:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/12689/">publish-testray-report#12689</a><br/></div></div>

2022-10-03 17:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4636/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4636/jenkins-report.html">here</a>.</b></p>

2022-10-03 17:46 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4636//consoleFull)

2022-10-03 17:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/4636/">test-portal-acceptance-pullrequest(master)#4636</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4636/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/609">joshchong#609</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1996683413">[master] ci:test:relevant - brookedalton &gt; joshchong - PR#609 - 2022-10-03[10:42:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/11427/">publish-testray-report#11427</a><br/></div></div>