LPS-182278
joshchong/liferay-portal pull request #701
Opened 2023-05-08 20:43 UTC by CaiocSiqueira

2023-05-08 20:43 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-08 20:44 UTC, CaiocSiqueira commented
ci:test:sf

2023-05-08 20:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/5494/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5494/jenkins-report.html">here</a>.</b></p>

2023-05-08 20:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/576a6c09f5f21bd0fb6d556c08bf678c242f34f6">576a6c09f5f21bd0fb6d556c08bf678c242f34f6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-182278">LPS-182278</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/acf8254c1794ae67a51380724737bae09ea240b9">acf8254c1794ae67a51380724737bae09ea240b9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5494/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5494/jenkins-report.html">here</a>.</h5></details></html>

2023-05-08 20:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5494/">test-portal-source-format#5494</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5494/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/701">joshchong#701</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2297840737">[master] ci:test:sf - CaiocSiqueira &gt; joshchong - PR#701 - 2023-05-08[13:44:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/21039/">publish-testray-report#21039</a><br/></div></div>

2023-05-12 23:57 UTC, joshchong requested changes

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		task ("Create object and add fields to it") {
Reword task to "Create a site scoped object and add the following fields to it: 'title' as a keyword, 'siteID' as an integer, and 'date' as a date"

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +				pluralLabelName = "Custom Objects",
pass in the following variable: `panelCategoryKey = "site_administration.content",` so that you don't have to set up category key via UI with `CreateObject.selectPanelCategoryKey` below

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			CreateObject.saveObject();
You can delete all of this so we don't use any UI to set up the object.  Instead create this new macro in JSONObject.macro:
```	
	@summary = "This calls the patchObjectDefinition Headless API endpoint to update a configuration within an object definition"
	macro updateObject {
		var portalURL = JSONCompany.getPortalURL();
		var objectId = JSONObject.getObjectId(objectName = ${objectName});

		if (!(isSet(userEmailAddress))) {
			var userEmailAddress = "test@liferay.com";
		}

		if (!(isSet(userPassword))) {
			var userPassword = "test";
		}

		var curl = '''
			${portalURL}/o/object-admin/v1.0/object-definitions/${objectId} \
				-H 'Content-Type: application/json' \
				-u ${userEmailAddress}:${userPassword} \
				-d '{
					"${configKey}": "${configValue}"
				}'
		''';

		JSONCurlUtil.patch(${curl});
	}
```
And update the title by calling the macro like so:
```		
JSONObject.updateObject(
	configKey = "titleObjectFieldName",
	configValue = "title",
	objectName = "CustomObject");
```

Note that you will have to use that macro before publishing the object though. so call it before `ObjectAdmin.publishObjectViaAPI`

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		task ("Create three object entries") {
Refactor this entire task to create the object entries via json api. create the following new macro in JSONObject.macro:

```
	@summary = "This calls the JSON WS API to create an Objects entry with any number of fields"
	macro addObjectEntryViaJSONAPI {
		var portalURL = JSONCompany.getPortalURL();

		if (!(isSet(userEmailAddress))) {
			var userEmailAddress = "test@liferay.com";
		}

		if (!(isSet(userPassword))) {
			var userPassword = "test";
		}

		if (!(isSet(groupName))) {
			var groupName = "Guest";
		}

		var groupId = JSONGroupAPI._getGroupIdByName(
			groupName = ${groupName},
			site = "true");
		var objectId = JSONObject.getObjectId(
			objectName = ${objectName},
			userEmailAddress = ${userEmailAddress},
			userPassword = ${userPassword});
		var objectName = StringUtil.toLowerCase(${objectName});

		if (!(isSet(fieldList))) {
			Variables.assertDefined(parameterList = "${fieldName},${fieldValue}");

			var entryValues = "{\"${fieldName}\": \"${fieldValue}\"}";
		} else {
			Variables.assertDefined(parameterList = "${fieldList}");

			var fieldList = ListUtil.newListFromString(${fieldList});

			var sb = "{";

			for (var fieldNameValue : list ${fieldList}) {
				var fieldName = StringUtil.extractFirst(${fieldNameValue}, "/");
				var fieldValue = StringUtil.extractLast(${fieldNameValue}, "/");

				sb = "${sb}\"${fieldName}\": \"${fieldValue}\"";

				ListUtil.remove(${fieldList}, ${fieldNameValue});

				var size = ListUtil.size(${fieldList});

				var listEmpty = ListUtil.isEmpty(${fieldList});

				if (${listEmpty} == "false") {
					sb = "${sb},";
				}
			}

			var entryValues = "${sb}}";
		}

		var curl = '''
			${portalURL}/api/jsonws/object.objectentry/add-object-entry \
				-u ${userEmailAddress}:${userPassword} \
				-d groupId=${groupId} \
				-d objectDefinitionId=${objectId} \
				-d values=${entryValues}
		''';

		JSONCurlUtil.post(${curl});
	}
```

then create the entry like so:
```
		JSONObject.addObjectEntryViaJSONAPI(
			fieldList = "title/Apple Fruit,siteID/2,date/2023-04-03",
			objectName = "CustomObject");
```

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		task ("Create Blueprint with 'ascending by Title' sort configuration in it") {
update task to "Create a Blueprint"

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		}
Add a new task for these lines that reads "Configure the blueprint Sort Configuration to sort by the custom object's 'title' field in ascending order"

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		task ("Assert that preview results are sorted ascending by Title") {
update task to "Assert that the blueprint preview results are sorted based on the Sort Configuration above"

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		task ("Update the sort configuration to sort by Site ID ascending and assert it") {
Update task to "Update the blueprint Sort Configuration to sort by the custom object's 'siteID' field in ascending order"

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +				var count = ${count} + 1;
Add a new task for these lines that reads "Assert that the blueprint preview results are sorted based on the Sort Configuration above"

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		task ("Update the sort configuration to sort by date ascending and assert it") {
Update / add new tasks in the same way as the ones above

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		task ("Update the sort configuration to sort by date descending and assert it") {
Update / add new tasks in the same way as the ones above

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +			var count = 1;
update "count" variable to "ranking". do this for the rest of test where it applies.

2023-05-12 23:57 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +				locator1 = "Button#ANY");
use `Blueprints#BLUEPRINTS_PREVIEW_REFRESH_SEARCH_BUTTON` instead for this and the rest of the test.

2023-05-12 23:59 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase
> +		task ("Create three object entries") {
also delete `macro addObjectSingleFieldEntryViaJSONAPI` and update all tests to use `JSONObject.addObjectEntryViaJSONAPI` instead

2023-05-19 20:12 UTC, joshchong commented
@CaiocSiqueira forwarding in https://github.com/joshchong/liferay-portal/pull/720. please see changes. thanks!

2023-05-19 20:12 UTC, closed without merging