LPS-181083
joshchong/liferay-portal pull request #703
Opened 2023-05-09 21:57 UTC by CaiocSiqueira

2023-05-09 21:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-09 21:58 UTC, CaiocSiqueira commented
ci:test:sf

2023-05-09 22:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/5503/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5503/jenkins-report.html">here</a>.</b></p>

2023-05-09 22:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/56ea09f602ee231f3292ead33b58caf70c02a67d">56ea09f602ee231f3292ead33b58caf70c02a67d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-181083">LPS-181083</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/91d1341b837c88df8d0f8e03bcfa6144c089ef22">91d1341b837c88df8d0f8e03bcfa6144c089ef22</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5503/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5503/jenkins-report.html">here</a>.</h5></details></html>

2023-05-09 22:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5503/">test-portal-source-format#5503</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5503/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/703">joshchong#703</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2299323421">[master] ci:test:sf - CaiocSiqueira &gt; joshchong - PR#703 - 2023-05-09[14:58:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/21080/">publish-testray-report#21080</a><br/></div></div>

2023-05-15 19:56 UTC, joshchong requested changes

2023-05-15 19:56 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +		task ("Edit sort widget configuration") {
Rework this entire task block by doing the following:
- For adding a sort option, create and use a macro called SearchPortlets.addSortOption that accepts a variable for each field of the sort option
- Don't use for loops for this
- Add a task for each sort option added giving a short description of what you are sorting by

2023-05-15 19:56 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +			Search.openSearchPage();
delete this as it's redundant

2023-05-15 19:56 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +			SearchPortlets.addWidgets(searchPortletList = "Sort");
use JSONLayout.addWidgetToPublicLayout

2023-05-15 19:56 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +		task ("Create object with Title, Date and Site ID fields in it") {
Make the same suggestion for creating the object definition and entries from the review here: https://github.com/joshchong/liferay-portal/pull/701#pullrequestreview-1425248913

2023-05-19 20:12 UTC, joshchong commented
@CaiocSiqueira forwarding in https://github.com/joshchong/liferay-portal/pull/720. please see changes. thanks!

2023-05-19 20:12 UTC, closed without merging