LPS-181082
joshchong/liferay-portal pull request #705
Opened 2023-05-10 16:36 UTC by CaiocSiqueira

2023-05-10 16:36 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-10 16:45 UTC, CaiocSiqueira commented
ci:test:sf

2023-05-10 16:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/5155/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5155/jenkins-report.html">here</a>.</b></p>

2023-05-10 16:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/73ab9bf82e0d38f99fabc6a51416cfe7bc2f07d1">73ab9bf82e0d38f99fabc6a51416cfe7bc2f07d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-181082">LPS-181082</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/30760ed1dbcb833051e162ec14ccaea9835521be">30760ed1dbcb833051e162ec14ccaea9835521be</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5155/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5155/jenkins-report.html">here</a>.</h5></details></html>

2023-05-10 16:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5155/">test-portal-source-format#5155</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5155/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/705">joshchong#705</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2300180285">[master] ci:test:sf - CaiocSiqueira &gt; joshchong - PR#705 - 2023-05-10[09:47:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/2884/">publish-testray-report#2884</a><br/></div></div>

2023-05-12 21:26 UTC, CaiocSiqueira commented
ci:test:sf

2023-05-12 21:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/2391/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2391/jenkins-report.html">here</a>.</b></p>

2023-05-12 21:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fe3c34314ebba0343bb825d9ca88b405c2a1f96d">fe3c34314ebba0343bb825d9ca88b405c2a1f96d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-181082">LPS-181082</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/7159da55d232cb36c5534fefaf05f0bb1cb9bbfb">7159da55d232cb36c5534fefaf05f0bb1cb9bbfb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2391/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2391/jenkins-report.html">here</a>.</h5></details></html>

2023-05-12 21:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2391/">test-portal-source-format#2391</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2391/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/705">joshchong#705</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2302693845">[master] ci:test:sf - CaiocSiqueira &gt; joshchong - PR#705 - 2023-05-12[14:27:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/9450/">publish-testray-report#9450</a><br/></div></div>

2023-05-15 18:46 UTC, joshchong requested changes

2023-05-15 18:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SearchFacets.testcase
> +		task ("Configure the Custom Facet widget aggregation field and check the coconut fruit checkbox") {
Update task to "Configure the Custom Facet widget to aggregate by the 'title' custom Object field"

2023-05-15 18:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SearchFacets.testcase
> +			Click.clickAtNotVisible(
Add task "Assert 'title' facet terms are present and check one"

2023-05-15 18:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SearchFacets.testcase
> +		task ("Assert that only Coconut Fruit is present") {
Update task to "Assert only search results associated with the checked facet term are returned"

2023-05-15 18:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SearchFacets.testcase
> +		task ("Configure the Custom Facet widget aggregation field and check the '1' checkbox") {
update tasks to follow new pattern in comments above.

2023-05-15 18:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SearchFacets.testcase
> +		task ("Configure the Custom Facet widget aggregation field and check the only date checkbox that is shown") {
update tasks to follow new pattern in comments above.

2023-05-15 18:46 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SearchFacets.testcase
> +		task ("Create object with Title, Date and Site ID fields in it") {
Make the same suggestion for creating the object definition and entries from the review here: https://github.com/joshchong/liferay-portal/pull/701#pullrequestreview-1425248913

2023-05-15 19:55 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SearchFacets.testcase
> +			Search.openSearchPage();
delete this

2023-05-19 20:12 UTC, joshchong commented
@CaiocSiqueira forwarding in https://github.com/joshchong/liferay-portal/pull/720. please see changes. thanks!

2023-05-19 20:12 UTC, closed without merging