LPS-181084
joshchong/liferay-portal pull request #722
Opened 2023-05-23 15:47 UTC by CaiocSiqueira

2023-05-23 15:48 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-23 15:52 UTC, CaiocSiqueira commented
ci:test:sf

2023-05-23 15:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/6335/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/6335/jenkins-report.html">here</a>.</b></p>

2023-05-23 16:38 UTC, joshchong requested changes

2023-05-23 16:38 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +				locator1 = "Search#CUSTOM_FILTER_WIDGET_TEXT_BAR",
Rename path to CUSTOM_FILTER_WIDGET_VALUE_INPUT

2023-05-23 16:38 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +				searchAssetTitle = "apple fruit",
Capitalize Apple Fruit

2023-05-23 16:38 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +				locator1 = "Button#ANY_LAST");
Can you take this method of filtering and update Search#FilterByDDMFields to use it as well? specifically in the task that reads "Use the third Custom Filter widget to filter by the DDM field value of the first web content structure article"

2023-05-23 16:38 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +				objectName = "CustomObject");
When just creating a single object entry, split up the field name and field value instead of putting it in fieldList i.e. use fieldName and fieldValue instead.

2023-05-23 16:38 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +				objectName = "CustomObject");
When just creating a single object entry, split up the field name and field value instead of putting it in fieldList i.e. use fieldName and fieldValue instead.

2023-05-23 16:38 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase
> +	@priority = 3
Add a description that reads "LPS-172376 - The Custom Filter widget supports filtering by custom Object fields"

2023-05-23 16:48 UTC, joshchong requested changes
what was the point of this change?

2023-05-23 18:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5012/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5012/jenkins-report.html">here</a>.</b></p>

2023-05-23 18:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f83f1261268364863a34922cc7e15ab3bf344d2c">f83f1261268364863a34922cc7e15ab3bf344d2c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-181084">LPS-181084</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/322d46481a6e13caeeba37c28e9a57473d47baf2">322d46481a6e13caeeba37c28e9a57473d47baf2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5012/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5012/jenkins-report.html">here</a>.</h5></details></html>

2023-05-23 18:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5012/">test-portal-source-format#5012</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5012/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/722">joshchong#722</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2317184972">[master] ci:test:sf - CaiocSiqueira &gt; joshchong - PR#722 - 2023-05-23[11:33:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18709/">publish-testray-report#18709</a><br/></div></div>

2023-05-25 17:27 UTC, joshchong commented
@CaiocSiqueira see minor changes in: https://github.com/joshchong/liferay-portal/pull/724

2023-05-25 17:27 UTC, closed without merging