LPS-194321
joshchong/liferay-portal pull request #807
Opened 2023-09-19 16:49 UTC by CaiocSiqueira

2023-09-19 16:49 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-19 20:18 UTC, joshchong requested changes
Please see requested changes. Also can you move the ReindexSearchTuningWithSyncExecutionMode test and ReindexSearchTuningWithConcurrentExecutionMode tests to SeachTuningES7.testcase? I realized it would be more appropriate there. do this in a separate commit so we can more easily see the changes you made to the test in other commits

2023-09-19 20:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/elasticsearch/Elasticsearch7.testcase
> +		task ("Begin a Result Rankings index reindex using sync execution mode") {
move all your changes to after the task `After the reindex is complete, assert the timestamp values for both the result ranking and the synonym set are updated in the index`

2023-09-19 20:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/elasticsearch/Elasticsearch7.testcase
> +		task ("Begin a Result Rankings index reindex using sync execution mode") {
Reword task to "Reindex the individual Result Rankings index using sync execution mode"

2023-09-19 20:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/elasticsearch/Elasticsearch7.testcase
> +		task ("Begin a Synonym Set reindex using sync execution mode") {
Reword task to "Reindex the individual Synonym Set index using sync execution mode"

2023-09-19 20:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/elasticsearch/Elasticsearch7.testcase
> +		task ("Assert that the synonym set is still available in the UI during the reindex") {
Reword task to "Assert the Synonym set is still present within Synonyms admin"

2023-09-19 20:18 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/elasticsearch/Elasticsearch7.testcase
> +		task ("Assert that the Result Rankings is still available in the UI during the reindex") {
Reword task to "Assert the ranking is still present within Result Rankings admin"

2023-09-21 16:40 UTC, CaiocSiqueira commented
ci:test:sf

2023-09-21 16:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/4874/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4874/jenkins-report.html">here</a>.</b></p>

2023-09-21 16:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6e716e8827644e1619318501f5d5243dea45fe8b">6e716e8827644e1619318501f5d5243dea45fe8b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-194321">LPS-194321</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/2dad623f1c43de2cd30d1755fa0382270d0b2311">2dad623f1c43de2cd30d1755fa0382270d0b2311</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4874/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4874/jenkins-report.html">here</a>.</h5></details></html>

2023-09-21 16:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4874/">test-portal-source-format#4874</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4874/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/807">joshchong#807</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2428926815">[master] ci:test:sf - CaiocSiqueira &gt; joshchong - PR#807 - 2023-09-21[09:41:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/4653/">publish-testray-report#4653</a><br/></div></div>

2023-09-21 21:29 UTC, joshchong requested changes
hey @CaiocSiqueira, if possible can you split the test move into and the test improvement into separate commits? once you complete all these changes, you can forward to bchan if sf passes.

2023-09-21 21:29 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/elasticsearch/SearchTuningES7.testcase
> +			WaitForElementNotPresent(locator1 = "Search#REINDEX_IN_PROGRESS_INDICATOR");
you can delete these steps. they aren't needed anymore since the test is already within the index actions page and the test already waited for the reindex to happen earlier

2023-09-21 21:29 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/elasticsearch/SearchTuningES7.testcase
> +			WaitForElementNotPresent(locator1 = "Search#REINDEX_IN_PROGRESS_INDICATOR");
you can remove this one as well since we don't need to wait for the other ranking reindex to finish

2023-09-21 21:36 UTC, CaiocSiqueira commented
ci:test:sf

2023-09-21 21:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/5723/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5723/jenkins-report.html">here</a>.</b></p>

2023-09-21 21:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ab84df048550a82e8b3762e30566b4f14ba0fda5">ab84df048550a82e8b3762e30566b4f14ba0fda5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-194321">LPS-194321</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/35d90a2f718981c31d140899003cb67fba9f3a7c">35d90a2f718981c31d140899003cb67fba9f3a7c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5723/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5723/jenkins-report.html">here</a>.</h5></details></html>

2023-09-21 21:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/5723/">test-portal-source-format#5723</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/5723/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/807">joshchong#807</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2429135544">[master] ci:test:sf - CaiocSiqueira &gt; joshchong - PR#807 - 2023-09-21[14:36:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/21921/">publish-testray-report#21921</a><br/></div></div>

2023-09-21 22:10 UTC, CaiocSiqueira commented
ci:test:sf

2023-09-21 22:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7371/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7371/jenkins-report.html">here</a>.</b></p>

2023-09-21 22:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ab84df048550a82e8b3762e30566b4f14ba0fda5">ab84df048550a82e8b3762e30566b4f14ba0fda5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-194321">LPS-194321</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/f3ceb17dda9c003427c49a0925891c052a7f6b5b">f3ceb17dda9c003427c49a0925891c052a7f6b5b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7371/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7371/jenkins-report.html">here</a>.</h5></details></html>

2023-09-21 22:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7371/">test-portal-source-format#7371</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7371/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/joshchong/liferay-portal/pull/807">joshchong#807</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2429149356">[master] ci:test:sf - CaiocSiqueira &gt; joshchong - PR#807 - 2023-09-21[15:11:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27472/">publish-testray-report#27472</a><br/></div></div>

2023-09-22 13:39 UTC, CaiocSiqueira commented
ci:forward

2023-09-22 13:39 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-09-22 13:39 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-09-22 13:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/745//consoleFull)

2023-09-22 14:15 UTC, closed without merging

2023-09-22 14:15 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/141172
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/745//consoleFull)